New CalibrationViewer helper object for nice printing of backend calibration data
QuTech-Delft/quantuminspire pull request #120
Opened 2021-11-08 11:17 UTC by codecrap

This is a proposal for a CalibrationViewer helper object to nicely handle and print backend calibration data.
It uses rich printing but falls back to the builtin print if not available.
I will add more tests and further refine the class if it is in principle okay to include this helper object in the main repo.

An example of its use is currently available in [the examples repo](https://github.com/QuTech-Delft/quantum-inspire-examples/blob/feat/example_calibration_retrieval/docs/notebooks/example_calibration_data.ipynb), or [an updated version](https://github.com/codecrap/quantum-inspire-examples/blob/feat/example_calibration_retrieval/docs/notebooks/example_calibration_data.ipynb).

2021-11-12 17:55 UTC, codecrap commented
The pipeline is failing because it tries to run a notebook that requires authentication, which it doesn't receive and thus the build times out. The same test does not seem to be a problem for #121 (https://github.com/QuTech-Delft/quantuminspire/pull/121). Can you help out with this issue @QFer ?

2021-11-15 07:40 UTC, QFer commented
@codecrap The reason is that pull requests sent from forked repositories do not have access to encrypted authentication secrets needed for running the tests on quantum inspire backend.
A possible solution is to disable these example runs for pull requests.

2021-11-15 14:15 UTC, QFer commented
@codecrap I made a change so the pull request coming from a fork is not running the examples.  While reviewing and before merging we will run the examples and check correctness. Please add unit test to coverage 100% and I guess your (out-of-date) branch needs a rebase or merge.

2021-12-13 12:44 UTC, peendebak commented on src/quantuminspire/calibration_viewer.py
> +
Add docstring for parameter `field`

2021-12-13 12:44 UTC, peendebak commented on src/quantuminspire/calibration_viewer.py
> +
Missing docstring for `field`

2021-12-13 12:44 UTC, peendebak commented on src/quantuminspire/calibration_viewer.py
> +    def timestamp(self) -> str:
Add docstring

2021-12-20 09:39 UTC, codecrap commented on src/quantuminspire/calibration_viewer.py
> +
Fixed in new commit

2021-12-20 09:39 UTC, codecrap commented on src/quantuminspire/calibration_viewer.py
> +
Fixed in new commit

2021-12-20 09:39 UTC, codecrap commented on src/quantuminspire/calibration_viewer.py
> +    def timestamp(self) -> str:
Fixed in new commit

2022-01-17 11:33 UTC, QFer requested changes

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +                        rprint(f"Key 'timestamp' not in item {item}.")
1. the method is called: show_system_parameters so I expect the system structure to be printed. But what I get is only a timestamp?
2. when timestamp is not in the structure we get lines with key 'timestamp' not in messages. Why not just print item in this case as I would expect from the method name (and as done in show_qubit_parameters)

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +                rprint(f"Unknown structure '{key}' in system calibration.")
Actually key is not the unknown structure but item is. The message is misleading.

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +                    rprint(f"Unknown structure '{key}' in qubit calibration.")
Same here: key is not the unknown structure but item is. The message is misleading.

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +        cal = self.get_calibration_field(field)
cal -> calibration_field

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +        return cal
This return is odd. For this we have method get_calibration_field. I don't expect a method that is called show_calibration_field to return something.

2022-01-17 11:33 UTC, QFer commented on src/tests/quantuminspire/test_calibrationviewer.py
> +                                                'unknown_field': [0,1,2]
```suggestion
                                                'unknown_field': [0, 1, 2]
```

2022-01-17 11:33 UTC, QFer commented on src/tests/quantuminspire/test_calibrationviewer.py
> +                                                    'unknown_field': [0,1,2]
```suggestion
                                                    'unknown_field': [0, 1, 2]
```

2022-01-17 11:33 UTC, QFer commented on src/tests/quantuminspire/test_calibrationviewer.py
> +
remove 1 newline

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +        rprint(f"\t{str(other_fields)}")
When I call a method show_calibration_field I expect that the fields are printed but now it only prints some predefined values and the other key values of the structure and not the values? What is the idea behind this?

Why not just print the calibration field as expected?

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +        Print calibration for a specific key `field` and return the content.
This is what I expect but it doesn't do this. It doesn't print the field when 'value' key is part of the structure.

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +        for key in simple_keys:
When 'value' is not part of cal the complete structure is printed. Why bother printing these values again

2022-01-17 11:33 UTC, QFer commented on src/quantuminspire/calibration_viewer.py
> +        cal = self.get_calibration_field(field)
This call to get_calibration_field may raise an exception. Do you want this show_calibration_field raise this exception when a non-exiting field is entered or handle it differnetly?

2024-03-24 20:13 UTC, closed without merging